// This file is auto-generated by gen_ops.py
// Do not edit this file directly.
namespace Ws2Explorer.Compiler;

/// <summary>
/// List of opcodes and pseudo-opcodes.
/// Negative values are pseudo-opcodes used to signal special meaning to the compiler.
/// These opcodes do not appear in the binary (but their arguments may).
/// </summary>
public static class Opcode
{
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member

    public const int VERSION = -1;
    public const int LABEL = -2;

    public const byte WS2_NULL_00 = 0x00;
    public const byte WS2_CONDITIONAL_JUMP_01 = 0x01;
    public const byte WS2_JUMP_02 = 0x02;
    public const byte WS2_CALL_FILE_04 = 0x04;
    public const byte WS2_JUMP_06 = 0x06;
    public const byte WS2_JUMP_FILE_07 = 0x07;
    public const byte WS2_MODIFY_VARIABLE_09 = 0x09;
    public const byte WS2_SET_FLAG_0B = 0x0B;
    public const byte WS2_SHOW_CHOICE_0F = 0x0F;
    public const byte WS2_SET_TIMER_11 = 0x11;
    public const byte WS2_START_TIMER_12 = 0x12;
    public const byte WS2_DISPLAY_TEXT_14 = 0x14;
    public const byte WS2_DISPLAY_NAME_15 = 0x15;
    public const byte WS2_OPEN_TITLE_1A = 0x1A;
    public const byte WS2_CALL_LUA_1C = 0x1C;
    public const byte WS2_PLAY_MUSIC_1E = 0x1E;
    public const byte WS2_STOP_MUSIC_1F = 0x1F;
    public const byte WS2_MUSIC_UNKNOWN_20 = 0x20;
    public const byte WS2_PLAY_SOUND_28 = 0x28;
    public const byte WS2_STOP_SOUND_29 = 0x29;
    public const byte WS2_SOUND_UNKNOWN_2A = 0x2A;
    public const byte WS2_START_DISPLAY_TEXT_2E = 0x2E;
    public const byte WS2_SET_BACKGROUND_33 = 0x33;
    public const byte WS2_LOAD_PNA_34 = 0x34;
    public const byte WS2_PLAY_MOVIE_35 = 0x35;
    public const byte WS2_CLEAR_LAYER_37 = 0x37;
    public const byte WS2_VARIABLE_UNKNOWN_38 = 0x38;
    public const byte WS2_DISPLAY_PNA_39 = 0x39;
    public const byte WS2_BACKGROUND_UNKNOWN_3A = 0x3A;
    public const byte WS2_ORDER_LAYERS_3F = 0x3F;
    public const byte WS2_SET_MASK_40 = 0x40;
    public const byte WS2_BACKGROUND_UNKNOWN_41 = 0x41;
    public const byte WS2_GET_LAYER_PROPERTY_45 = 0x45;
    public const byte WS2_SET_LAYER_PROPERTY_46 = 0x46;
    public const byte WS2_EFFECT_47 = 0x47;
    public const byte WS2_EFFECT_48 = 0x48;
    public const byte WS2_LOAD_ANIMATION_FRAME_51 = 0x51;
    public const byte WS2_VARIABLE_UNKNOWN_52 = 0x52;
    public const byte WS2_VARIABLE_UNKNOWN_53 = 0x53;
    public const byte WS2_START_RAIN_56 = 0x56;
    public const byte WS2_BACKGROUND_UNKNOWN_57 = 0x57;
    public const byte WS2_EFFECT_58 = 0x58;
    public const byte WS2_STOP_RAIN_5C = 0x5C;
    public const byte WS2_SHOW_EFFECT_MASK_66 = 0x66;
    public const byte WS2_SET_NAMED_VARIABLE_6E = 0x6E;
    public const byte WS2_VARIABLE_UNKNOWN_6F = 0x6F;
    public const byte WS2_SCREEN_UNKNOWN_F0 = 0xF0;
    public const byte WS2_FILE_END_FF = 0xFF;

    public const byte WSC_CONDITIONAL_01 = 0x01;
    public const byte WSC_SHOW_CHOICE_02 = 0x02;
    public const byte WSC_CALCULATE_03 = 0x03;
    public const byte WSC_QUIT_04 = 0x04;
    public const byte WSC_WAIT_TIMER_05 = 0x05;
    public const byte WSC_JUMP_06 = 0x06;
    public const byte WSC_JUMP_FILE_07 = 0x07;
    public const byte WSC_SET_TEXT_SIZE_08 = 0x08;
    public const byte WSC_CALL_FILE_09 = 0x09;
    public const byte WSC_RETURN_0A = 0x0A;
    public const byte WSC_SET_TIMER_0B = 0x0B;
    public const byte WSC_CHECK_TIMER_0C = 0x0C;
    public const byte WSC_PLAY_MUSIC_21 = 0x21;
    public const byte WSC_STOP_MUSIC_22 = 0x22;
    public const byte WSC_PLAY_VOICE_23 = 0x23;
    public const byte WSC_PLAY_SOUND_25 = 0x25;
    public const byte WSC_STOP_SOUND_26 = 0x26;
    public const byte WSC_DISPLAY_TEXT_41 = 0x41;
    public const byte WSC_DISPLAY_TEXT_AND_NAME_42 = 0x42;
    public const byte WSC_LOAD_ANIMATION_43 = 0x43;
    public const byte WSC_ENABLE_ANIMATION_45 = 0x45;
    public const byte WSC_LOAD_BACKGROUND_46 = 0x46;
    public const byte WSC_SET_BACKGROUND_COLOUR_47 = 0x47;
    public const byte WSC_LOAD_CHARACTER_GRAPHICS_48 = 0x48;
    public const byte WSC_CLEAR_CENTRE_OVERLAY_49 = 0x49;
    public const byte WSC_SET_TRANSITION_4A = 0x4A;
    public const byte WSC_ADD_ANIMATION_4B = 0x4B;
    public const byte WSC_PLAY_ANIMATION_4C = 0x4C;
    public const byte WSC_LOAD_EFFECT_4D = 0x4D;
    public const byte WSC_DISABLE_ANIMATION_4F = 0x4F;
    public const byte WSC_LOAD_TABLE_50 = 0x50;
    public const byte WSC_SELECT_TABLE_ITEM_51 = 0x51;
    public const byte WSC_DELAY_SOUND_52 = 0x52;
    public const byte WSC_LOAD_TRANSPARENT_IMAGE_54 = 0x54;
    public const byte WSC_PLAY_VIDEO_61 = 0x61;
    public const byte WSC_SHOW_CHARACTER_INFO_64 = 0x64;
    public const byte WSC_SET_BACKGROUND_SIZE_AND_POSITION_68 = 0x68;
    public const byte WSC_CGWAIT_72 = 0x72;
    public const byte WSC_ADD_OVERLAY_73 = 0x73;
    public const byte WSC_CLEAR_OVERLAY_74 = 0x74;
    public const byte WSC_DELAY_EXECUTION_82 = 0x82;
    public const byte WSC_LOAD_GAME_83 = 0x83;
    public const byte WSC_NEW_GAME_84 = 0x84;
    public const byte WSC_CONFIGURATION_SCREEN_8B = 0x8B;
    public const byte WSC_CLEAR_RIGHT_OVERLAY_B8 = 0xB8;
    public const byte WSC_SCENE_TITLE_E0 = 0xE0;
    public const byte WSC_QUICK_LOAD_E2 = 0xE2;
    public const byte WSC_FILE_END_FF = 0xFF;

#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member
}
