static class FileList {
    public static readonly List<(string src, string dst)> COPY_FILES = new() {
        ("Voice.arc", "Voice.arc"),
        ("Voice1.arc", "Voice1.arc"),
        ("Graphic.arc", "Graphic_JP.arc"),
    };

    public static readonly List<string> CHIP_FILES = new() {
        "Chip1.arc",
        "Chip1A.arc",
        "Chip2.arc",
        "Chip3.arc",
        "Chip3A.arc",
        "Chip3B.arc",
        "Chip4.arc",
    };

    public static readonly HashSet<string> JP_WS2_FILES = new() {
        "yozora_koro_114b.ws2",
        "yozora_koro_115_H.ws2",
        "yozora_koro_116.ws2",
        "yozora_koro_120.ws2",
        "yozora_koro_121_H.ws2",
        "yozora_koro_122.ws2",
        "yozora_koro_123a.ws2",
        "yozora_koro_124_H.ws2",
        "yozora_koro_125.ws2",
        "yozora_koro_125b.ws2",
        "yozora_koro_126_H.ws2",
        "yozora_koro_127.ws2",
        "yozora_koro_130_ep1.ws2",
        "yozora_koro_131_H.ws2",
        "yozora_koro_132_ep2.ws2",
        "yozora_hika_103c.ws2",
        "yozora_hika_103d_H.ws2",
        "yozora_hika_103e.ws2",
        "yozora_hika_103f.ws2",
        "yozora_hika_103g_H.ws2",
        "yozora_hika_103h.ws2",
        "yozora_hika_108f.ws2",
        "yozora_hika_108g_H.ws2",
        "yozora_hika_108h.ws2",
        "yozora_hika_110b.ws2",
        "yozora_hika_110c_H.ws2",
        "yozora_hika_110d.ws2",
        "yozora_saya_101i.ws2",
        "yozora_saya_101j_H.ws2",
        "yozora_saya_102.ws2",
        "yozora_saya_102b.ws2",
        "yozora_saya_102c_H.ws2",
        "yozora_saya_102d.ws2",
        "yozora_saya_107a.ws2",
        "yozora_saya_107b_H.ws2",
        "yozora_saya_107c.ws2",
        "yozora_saya_107d_H.ws2",
        "yozora_saya_107e.ws2",
        "yozora_ori_114b.ws2",
        "yozora_ori_115_H.ws2",
        "yozora_ori_116.ws2",
        "yozora_ori_117b.ws2",
        "yozora_ori_118_H.ws2",
        "yozora_ori_119.ws2",
        "yozora_ori_122b.ws2",
        "yozora_ori_123_H.ws2",
        "yozora_ori_124.ws2",
        "yozora_ori_128.ws2",
        "yozora_ori_129_H.ws2",
        "yozora_ori_130.ws2",
    };
}
