on:
  push:
    tags:
      - 'Ws2Explorer-*'

name: Create Ws2Explorer release

jobs:
  build:
    name: Create Ws2Explorer Release
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8'

      - name: Build
        shell: pwsh
        run: |
          cd Ws2Explorer/Ws2Explorer.Gui
          $version = "${{ github.ref_name }}".Substring("Ws2Explorer-v".Length)
          dotnet publish -c Release /p:Version=$version
          mv bin/Release/net8.0-windows/publish ${{ github.ref_name }}
          Compress-Archive -Path ${{ github.ref_name }} -DestinationPath ${{ github.ref_name }}.zip
        
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: Ws2Explorer/Ws2Explorer.Gui/${{ github.ref_name }}.zip
